### ISSUE TITLE
Bug using Linux, probably is not able to remove characters from the end of the line.

### ISSUE THREAD

**Issue by khataei** [MiguelArenas/protasr#1]
## Steps to reproduce:

1- Download and place these file in the src folder  

	-https://storage.googleapis.com/khataei.site/ati/60_teleosts.nex  
	-https://storage.googleapis.com/khataei.site/ati/Gadus_morhua.pdb  
	-https://storage.googleapis.com/khataei.site/ati/Settings.txt  
2- Navigate to src folder and
3- Run `perl ProtASR_main.pl Setting.txt`

## Actual behavior:  
```
Sequence of taxa of the PDB sequence (length 0): 
Sequence of taxa of the PDB sequence "without gaps" (length 0): 
ERROR in 60_teleosts.nex!. Length of the sequence of the PDB in the alignment (0) is different to the length of the alignment (217) 
```
## Expected behavior:
No error.
### CPU:  Intel® Core™ i7-8565U Processor 8M Cache, up to 4.60 GHz
(Also tried on n1-standard-4 (4 vCPUs, 15 GB memory))

### OS:
Ubuntu 18.04.4 LTS-64

### Perl version:
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
### Software version:
ProtASR2.2VB

## Note:
I think the problem is with the differences that Linux and Windows use characters for defining a new line. Check the proposed fix section.

**Comment by khataei** [comment]
## Proposed fix:
Add this line after line #976 in `ProtASR_main.pl` file to remove `\r` ,carriage return, from the end of the variable:  <br> `$PDBtaxaFromAln =~ s/\r//g # Preffered`  
Or this line to keep only the numbers, letters, and underscores:  
`$PDBtaxaFromAln =~ s/\W//g # might not work if name has - `
<br>
#### Thanks,
Javad

**Comment by MiguelArenas** [comment]
Hi Javad,

Thanks for reporting me this bug and also for proposing a solution.
It is now fixed to allow text files made with windows.

Best wishes,
Miguel
